import { expect } from "@jest/globals";

export const specA = {
  stats: {
    duration: expect.any(Number),
    endedAt: expect.any(String),
    startedAt: expect.any(String),
    failures: 1,
    passes: 0,
    pending: 0,
    skipped: 0,
    suites: 1,
    tests: 1,
  },
  reporter: "spec",
  reporterStats: {
    suites: 1,
    tests: 1,
    passes: 0,
    pending: 0,
    failures: 1,
    start: expect.any(String),
    end: expect.any(String),
    duration: expect.any(Number),
  },
  spec: {
    // baseName: "a.spec.js",
    // specFileExtension: ".spec.js",
    // relativeToCommonRoot: "a.spec.js",
    // specType: "integration",
    fileExtension: ".js",
    fileName: "a",
    name: "a.spec.js",
    relative: "cypress/e2e/a.spec.js",
    absolute: expect.stringMatching("a.spec.js"),
  },
  error: null,
  video: expect.any(String),
  shouldUploadVideo: true,
  hooks: null,
  tests: [
    {
      testId: "r3",
      title: ["Failing test with 2 attempts", "should try 2 times"],
      state: "failed",
      body: "() => {\n    cy.wrap(false).should('be.true');\n  }",
      displayError:
        "AssertionError: Timed out retrying after 4000ms: expected false to be true\n    at Context.eval (webpack://cypress-13-demo/./cypress/e2e/a.spec.js:5:19)",
      attempts: [
        {
          state: "failed",
          error: {
            name: "AssertionError",
            message:
              "Timed out retrying after 4000ms: expected false to be true",
            stack: expect.any(String),
            codeFrame: {
              line: 5,
              column: 20,
              originalFile: "cypress/e2e/a.spec.js",
              relativeFile: "e2e/cypress-13-demo/cypress/e2e/a.spec.js",
              absoluteFile: expect.stringContaining("a.spec.js"),
              frame:
                "  3 |     retries: 2,\n  4 |   }, () => {\n> 5 |     cy.wrap(false).should('be.true');\n    |                    ^\n  6 |   });\n  7 | });\n  8 | ",
              language: "js",
            },
          },
          timings: expect.any(Object),
          failedFromHookId: null,
          wallClockStartedAt: expect.any(String),
          wallClockDuration: expect.any(Number),
          videoTimestamp: expect.any(Number),
          startedAt: expect.any(String),
          duration: expect.any(Number),
          screenshots: [
            {
              screenshotId: expect.any(String),
              name: null,
              testId: "r3",
              testAttemptIndex: 0,
              takenAt: expect.any(String),
              path: expect.any(String),
              height: expect.any(Number),
              width: expect.any(Number),
            },
          ],
        },
        {
          state: "failed",
          error: {
            name: "AssertionError",
            message:
              "Timed out retrying after 4000ms: expected false to be true",
            stack: expect.any(String),
            codeFrame: {
              line: 5,
              column: 20,
              originalFile: "cypress/e2e/a.spec.js",
              relativeFile: "e2e/cypress-13-demo/cypress/e2e/a.spec.js",
              absoluteFile: expect.stringContaining("a.spec.js"),
              frame:
                "  3 |     retries: 2,\n  4 |   }, () => {\n> 5 |     cy.wrap(false).should('be.true');\n    |                    ^\n  6 |   });\n  7 | });\n  8 | ",
              language: "js",
            },
          },
          timings: expect.anything(),
          failedFromHookId: null,
          wallClockStartedAt: expect.any(String),
          wallClockDuration: expect.any(Number),
          videoTimestamp: expect.any(Number),
          startedAt: expect.any(String),
          duration: expect.any(Number),
          screenshots: [
            {
              screenshotId: expect.any(String),
              name: null,
              testId: "r3",
              testAttemptIndex: 1,
              takenAt: expect.any(String),
              path: expect.any(String),
              height: expect.any(Number),
              width: expect.any(Number),
            },
          ],
        },
        {
          state: "failed",
          error: {
            name: "AssertionError",
            message:
              "Timed out retrying after 4000ms: expected false to be true",
            stack: expect.any(String),
            codeFrame: {
              line: 5,
              column: 20,
              originalFile: "cypress/e2e/a.spec.js",
              relativeFile: "e2e/cypress-13-demo/cypress/e2e/a.spec.js",
              absoluteFile: expect.stringContaining("a.spec.js"),
              frame:
                "  3 |     retries: 2,\n  4 |   }, () => {\n> 5 |     cy.wrap(false).should('be.true');\n    |                    ^\n  6 |   });\n  7 | });\n  8 | ",
              language: "js",
            },
          },
          timings: expect.anything(),
          failedFromHookId: null,
          wallClockStartedAt: expect.any(String),
          wallClockDuration: expect.any(Number),
          videoTimestamp: expect.any(Number),
          startedAt: expect.any(String),
          duration: expect.any(Number),
          screenshots: [
            {
              screenshotId: expect.any(String),
              name: null,
              testId: "r3",
              testAttemptIndex: 2,
              takenAt: expect.any(String),
              path: expect.any(String),
              height: expect.any(Number),
              width: expect.any(Number),
            },
          ],
        },
      ],
    },
  ],
};
export const specE = {
  stats: {
    duration: expect.any(Number),
    endedAt: expect.any(String),
    startedAt: expect.any(String),
    failures: 1,
    passes: 0,
    pending: 0,
    skipped: 0,
    suites: 1,
    tests: 1,
  },
  reporter: "spec",
  reporterStats: {
    suites: 1,
    tests: 1,
    passes: 0,
    pending: 0,
    failures: 1,
    start: expect.any(String),
    end: expect.any(String),
    duration: expect.any(Number),
  },
  spec: {
    // baseName: "e.spec.js",
    // specFileExtension: ".spec.js",
    // relativeToCommonRoot: "e.spec.js",
    // specType: "integration",
    fileExtension: ".js",
    fileName: "e",
    name: "cypress/e2e/e.spec.js",
    relative: "cypress/e2e/e.spec.js",
    absolute: expect.stringMatching("e.spec.js"),
  },
  error: null,
  video: expect.any(String),
  shouldUploadVideo: true,
  hooks: null,
  tests: [
    {
      testId: "r3",
      title: ["Should throw an error", "Should throw an error"],
      state: "failed",
      body: '() => {\n    throw new Error("test error");\n  }',
      displayError:
        "Error: test error\n    at Context.eval (webpack://cypress-13-demo/./cypress/e2e/e.spec.js:3:10)",
      attempts: [
        {
          state: "failed",
          error: {
            name: "Error",
            message: "test error",
            stack: expect.any(String),
            codeFrame: {
              line: 3,
              column: 11,
              originalFile: "cypress/e2e/e.spec.js",
              relativeFile: "e2e/cypress-13-demo/cypress/e2e/e.spec.js",
              absoluteFile: expect.stringContaining("a.spec.js"),
              frame:
                "  1 | describe('Should throw an error', () => {\n  2 |   it('Should throw an error', () => {\n> 3 |     throw new Error(\"test error\")\n    |           ^\n  4 |   });\n  5 | });\n  6 | ",
              language: "js",
            },
          },
          timings: null,
          failedFromHookId: null,
          wallClockStartedAt: expect.any(String),
          wallClockDuration: expect.any(Number),
          videoTimestamp: expect.any(Number),
          startedAt: expect.any(String),
          duration: expect.any(Number),
          screenshots: [
            {
              screenshotId: expect.any(String),
              name: "screenshot",
              testId: "r3",
              testAttemptIndex: 0,
              takenAt: expect.any(String),
              path: expect.any(String),
              height: 1440,
              width: 2560,
            },
          ],
        },
      ],
    },
  ],
};
export const specD = {
  stats: {
    duration: 1120,
    endedAt: "2023-09-14T03:08:39.327Z",
    startedAt: "2023-09-14T03:08:38.207Z",
    failures: 0,
    passes: 2,
    pending: 0,
    skipped: 0,
    suites: 1,
    tests: 2,
  },
  reporter: "spec",
  reporterStats: {
    suites: 1,
    tests: 2,
    passes: 2,
    pending: 0,
    failures: 0,
    start: "2023-09-14T03:08:38.209Z",
    end: "2023-09-14T03:08:39.330Z",
    duration: 1121,
  },
  spec: {
    fileExtension: ".js",
    baseName: "d.spec.js",
    fileName: "d",
    specFileExtension: ".spec.js",
    relativeToCommonRoot: "d.spec.js",
    specType: "integration",
    name: "cypress/e2e/d.spec.js",
    relative: "cypress/e2e/d.spec.js",
    absolute:
      "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/e2e/d.spec.js",
  },
  error: null,
  video:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/videos/d.spec.js.mp4",
  shouldUploadVideo: true,
  hooks: [
    {
      hookId: "h1",
      hookName: "before each",
      title: ['"before each" hook'],
      body: '() => {\n  const currentTest = cy.state("ctx").currentTest;\n  if (currentTest) {\n    handleBefore(currentTest);\n  }\n}',
    },
    {
      hookId: "h2",
      hookName: "before each",
      title: ['"before each" hook'],
      body: 'function () {\n    cy.visit("/");\n}',
    },
    {
      hookId: "h4",
      hookName: "after each",
      title: ['"after each" hook'],
      body: "function () {\n      self.sendLogsToPrinter(self.collectorState.getCurrentLogStackIndex(), self.collectorState.getCurrentTest());\n    }",
    },
    {
      hookId: "h5",
      hookName: "after each",
      title: ['"after each" hook'],
      body: '() => {\n  const currentTest = cy.state("ctx").currentTest;\n  if (currentTest) {\n    handleAfter(currentTest);\n  }\n}',
    },
    {
      hookId: "h3",
      hookName: "after all",
      title: ['"after all" hook'],
      body: "function () {\n      // Need to wait otherwise some last commands get omitted from logs.\n      cy.task(CONSTANTS.TASK_NAME_OUTPUT, null, {log: false});\n    }",
    },
  ],
  tests: [
    {
      testId: "r3",
      title: [
        "Passed test with screenshot, passed test with no screenshots",
        "should assert and take a screenshot",
      ],
      state: "passed",
      body: "() => {\n    // Assert that true is true\n    cy.wrap(true).should('be.true');\n\n    // Take a screenshot\n    cy.screenshot('internal-assert-screenshot');\n  }",
      displayError: null,
      attempts: [
        {
          state: "passed",
          error: null,
          timings: {
            lifecycle: 37,
            "before each": [
              { hookId: "h1", fnDuration: 12, afterFnDuration: 0 },
              { hookId: "h2", fnDuration: 155, afterFnDuration: 0 },
            ],
            test: { fnDuration: 735, afterFnDuration: 0 },
            "after each": [
              { hookId: "h4", fnDuration: 13, afterFnDuration: 1 },
              { hookId: "h5", fnDuration: 10, afterFnDuration: 1 },
            ],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:08:38.219Z",
          wallClockDuration: 980,
          videoTimestamp: 1209,
          startedAt: "2023-09-14T03:08:38.219Z",
          duration: 980,
          screenshots: [
            {
              screenshotId: "5n5yz",
              name: "internal-assert-screenshot",
              testId: "r3",
              testAttemptIndex: 0,
              takenAt: "2023-09-14T03:08:38.441Z",
              path: "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/screenshots/d.spec.js/internal-assert-screenshot.png",
              height: 1320,
              width: 2000,
            },
          ],
        },
      ],
    },
    {
      testId: "r4",
      title: [
        "Passed test with screenshot, passed test with no screenshots",
        "should assert that true is true",
      ],
      state: "passed",
      body: "() => {\n    cy.wrap(true).should('be.true');\n  }",
      displayError: null,
      attempts: [
        {
          state: "passed",
          error: null,
          timings: {
            lifecycle: 33,
            "before each": [
              { hookId: "h1", fnDuration: 6, afterFnDuration: 0 },
              { hookId: "h2", fnDuration: 55, afterFnDuration: 0 },
            ],
            test: { fnDuration: 2, afterFnDuration: 0 },
            "after each": [
              { hookId: "h4", fnDuration: 12, afterFnDuration: 0 },
              { hookId: "h5", fnDuration: 8, afterFnDuration: 1 },
            ],
            "after all": [{ hookId: "h3", fnDuration: 4, afterFnDuration: 0 }],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:08:39.201Z",
          wallClockDuration: 125,
          videoTimestamp: 2191,
          startedAt: "2023-09-14T03:08:39.201Z",
          duration: 125,
          screenshots: [],
        },
      ],
    },
  ],
};
export const specC = {
  stats: {
    duration: 68,
    endedAt: "2023-09-14T03:08:42.351Z",
    startedAt: "2023-09-14T03:08:42.283Z",
    failures: 0,
    passes: 0,
    pending: 1,
    skipped: 0,
    suites: 1,
    tests: 1,
  },
  reporter: "spec",
  reporterStats: {
    suites: 1,
    tests: 1,
    passes: 0,
    pending: 1,
    failures: 0,
    start: "2023-09-14T03:08:42.285Z",
    end: "2023-09-14T03:08:42.355Z",
    duration: 70,
  },
  spec: {
    fileExtension: ".js",
    baseName: "c.spec.js",
    fileName: "c",
    specFileExtension: ".spec.js",
    relativeToCommonRoot: "c.spec.js",
    specType: "integration",
    name: "cypress/e2e/c.spec.js",
    relative: "cypress/e2e/c.spec.js",
    absolute:
      "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/e2e/c.spec.js",
  },
  error: null,
  video:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/videos/c.spec.js.mp4",
  shouldUploadVideo: true,
  hooks: [
    {
      hookId: "h3",
      hookName: "after all",
      title: ['"after all" hook'],
      body: "function () {\n      // Need to wait otherwise some last commands get omitted from logs.\n      cy.task(CONSTANTS.TASK_NAME_OUTPUT, null, {log: false});\n    }",
    },
  ],
  tests: [
    {
      testId: "r3",
      title: ["Ignored test", "should be a skipped test"],
      state: "pending",
      body: "() => {\n    cy.wrap(false).should('be.true');\n  }",
      displayError: null,
      attempts: [
        {
          state: "pending",
          error: null,
          timings: {
            lifecycle: 36,
            "after all": [{ hookId: "h3", fnDuration: 5, afterFnDuration: 0 }],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:08:42.308Z",
          wallClockDuration: 42,
          videoTimestamp: 1167,
          startedAt: "2023-09-14T03:08:42.308Z",
          duration: 42,
          screenshots: [],
        },
      ],
    },
  ],
};
export const specB = {
  stats: {
    duration: 18120,
    endedAt: "2023-09-14T03:09:02.909Z",
    startedAt: "2023-09-14T03:08:44.789Z",
    failures: 1,
    passes: 2,
    pending: 0,
    skipped: 0,
    suites: 1,
    tests: 3,
  },
  reporter: "spec",
  reporterStats: {
    suites: 1,
    tests: 3,
    passes: 2,
    pending: 0,
    failures: 1,
    start: "2023-09-14T03:08:44.790Z",
    end: "2023-09-14T03:09:02.913Z",
    duration: 18123,
  },
  spec: {
    fileExtension: ".js",
    baseName: "b.spec.js",
    fileName: "b",
    specFileExtension: ".spec.js",
    relativeToCommonRoot: "b.spec.js",
    specType: "integration",
    name: "cypress/e2e/b.spec.js",
    relative: "cypress/e2e/b.spec.js",
    absolute:
      "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/e2e/b.spec.js",
  },
  error: null,
  video:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/videos/b.spec.js.mp4",
  shouldUploadVideo: true,
  hooks: [
    {
      hookId: "h1",
      hookName: "before each",
      title: ['"before each" hook'],
      body: '() => {\n  const currentTest = cy.state("ctx").currentTest;\n  if (currentTest) {\n    handleBefore(currentTest);\n  }\n}',
    },
    {
      hookId: "h2",
      hookName: "before each",
      title: ['"before each" hook'],
      body: 'function () {\n    cy.visit("/");\n}',
    },
    {
      hookId: "h4",
      hookName: "after each",
      title: ['"after each" hook'],
      body: "function () {\n      self.sendLogsToPrinter(self.collectorState.getCurrentLogStackIndex(), self.collectorState.getCurrentTest());\n    }",
    },
    {
      hookId: "h5",
      hookName: "after each",
      title: ['"after each" hook'],
      body: '() => {\n  const currentTest = cy.state("ctx").currentTest;\n  if (currentTest) {\n    handleAfter(currentTest);\n  }\n}',
    },
    {
      hookId: "h3",
      hookName: "after all",
      title: ['"after all" hook'],
      body: "function () {\n      // Need to wait otherwise some last commands get omitted from logs.\n      cy.task(CONSTANTS.TASK_NAME_OUTPUT, null, {log: false});\n    }",
    },
  ],
  tests: [
    {
      testId: "r3",
      title: [
        "Failing test with 2 attempts, passed test and flaky test with 2 attempts",
        "should try 2 times",
      ],
      state: "failed",
      body: "() => {\n    cy.wrap(false).should('be.true');\n  }",
      displayError:
        "AssertionError: Timed out retrying after 4000ms: expected false to be true\n    at Context.eval (webpack://cypress-13-demo/./cypress/e2e/b.spec.js:6:19)",
      attempts: [
        {
          state: "failed",
          error: {
            name: "AssertionError",
            message:
              "Timed out retrying after 4000ms: expected false to be true",
            stack:
              "    at Context.eval (webpack://cypress-13-demo/./cypress/e2e/b.spec.js:6:19)",
            codeFrame: {
              line: 6,
              column: 20,
              originalFile: "cypress/e2e/b.spec.js",
              relativeFile: "e2e/cypress-13-demo/cypress/e2e/b.spec.js",
              absoluteFile:
                "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/e2e/b.spec.js",
              frame:
                "  4 |     retries: 2,\n  5 |   }, () => {\n> 6 |     cy.wrap(false).should('be.true');\n    |                    ^\n  7 |   });\n  8 | \n  9 |   it('should assert that true is true', () => {",
              language: "js",
            },
          },
          timings: {
            lifecycle: 26,
            "before each": [
              { hookId: "h1", fnDuration: 10, afterFnDuration: 1 },
              { hookId: "h2", fnDuration: 129, afterFnDuration: 0 },
            ],
            test: { fnDuration: 4012, afterFnDuration: 274 },
            "after each": [
              { hookId: "h4", fnDuration: 25, afterFnDuration: 1 },
              { hookId: "h5", fnDuration: 43, afterFnDuration: 0 },
            ],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:08:44.800Z",
          wallClockDuration: 4526,
          videoTimestamp: 1156,
          startedAt: "2023-09-14T03:08:44.800Z",
          duration: 4526,
          screenshots: [
            {
              screenshotId: "mkbvr",
              name: "screenshot",
              testId: "r3",
              testAttemptIndex: 0,
              takenAt: "2023-09-14T03:08:48.985Z",
              path: "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/screenshots/b.spec.js/Failing test with 2 attempts, passed test and flaky test with 2 attempts -- should try 2 times (failed).png",
              height: 1440,
              width: 2560,
            },
          ],
        },
        {
          state: "failed",
          error: {
            name: "AssertionError",
            message:
              "Timed out retrying after 4000ms: expected false to be true",
            stack:
              "    at Context.eval (webpack://cypress-13-demo/./cypress/e2e/b.spec.js:6:19)",
            codeFrame: {
              line: 6,
              column: 20,
              originalFile: "cypress/e2e/b.spec.js",
              relativeFile: "e2e/cypress-13-demo/cypress/e2e/b.spec.js",
              absoluteFile:
                "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/e2e/b.spec.js",
              frame:
                "  4 |     retries: 2,\n  5 |   }, () => {\n> 6 |     cy.wrap(false).should('be.true');\n    |                    ^\n  7 |   });\n  8 | \n  9 |   it('should assert that true is true', () => {",
              language: "js",
            },
          },
          timings: {
            lifecycle: 29,
            "before each": [
              { hookId: "h1", fnDuration: 10, afterFnDuration: 0 },
              { hookId: "h2", fnDuration: 55, afterFnDuration: 0 },
            ],
            test: { fnDuration: 3991, afterFnDuration: 238 },
            "after each": [
              { hookId: "h4", fnDuration: 12, afterFnDuration: 1 },
              { hookId: "h5", fnDuration: 22, afterFnDuration: 0 },
            ],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:08:49.350Z",
          wallClockDuration: 4360,
          videoTimestamp: 5706,
          startedAt: "2023-09-14T03:08:49.350Z",
          duration: 4360,
          screenshots: [
            {
              screenshotId: "g496m",
              name: "screenshot",
              testId: "r3",
              testAttemptIndex: 1,
              takenAt: "2023-09-14T03:08:53.437Z",
              path: "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/screenshots/b.spec.js/Failing test with 2 attempts, passed test and flaky test with 2 attempts -- should try 2 times (failed) (attempt 2).png",
              height: 1440,
              width: 2560,
            },
          ],
        },
        {
          state: "failed",
          error: {
            name: "AssertionError",
            message:
              "Timed out retrying after 4000ms: expected false to be true",
            stack:
              "    at Context.eval (webpack://cypress-13-demo/./cypress/e2e/b.spec.js:6:19)",
            codeFrame: {
              line: 6,
              column: 20,
              originalFile: "cypress/e2e/b.spec.js",
              relativeFile: "e2e/cypress-13-demo/cypress/e2e/b.spec.js",
              absoluteFile:
                "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/e2e/b.spec.js",
              frame:
                "  4 |     retries: 2,\n  5 |   }, () => {\n> 6 |     cy.wrap(false).should('be.true');\n    |                    ^\n  7 |   });\n  8 | \n  9 |   it('should assert that true is true', () => {",
              language: "js",
            },
          },
          timings: {
            lifecycle: 51,
            "before each": [
              { hookId: "h1", fnDuration: 8, afterFnDuration: 0 },
              { hookId: "h2", fnDuration: 56, afterFnDuration: 0 },
            ],
            test: { fnDuration: 3998, afterFnDuration: 213 },
            "after each": [
              { hookId: "h4", fnDuration: 21, afterFnDuration: 0 },
              { hookId: "h5", fnDuration: 61, afterFnDuration: 0 },
            ],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:08:53.724Z",
          wallClockDuration: 4415,
          videoTimestamp: 10080,
          startedAt: "2023-09-14T03:08:53.724Z",
          duration: 4415,
          screenshots: [
            {
              screenshotId: "inwwk",
              name: "screenshot",
              testId: "r3",
              testAttemptIndex: 2,
              takenAt: "2023-09-14T03:08:57.842Z",
              path: "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/screenshots/b.spec.js/Failing test with 2 attempts, passed test and flaky test with 2 attempts -- should try 2 times (failed) (attempt 3).png",
              height: 1440,
              width: 2560,
            },
          ],
        },
      ],
    },
    {
      testId: "r4",
      title: [
        "Failing test with 2 attempts, passed test and flaky test with 2 attempts",
        "should assert that true is true",
      ],
      state: "passed",
      body: "() => {\n    cy.wrap(true).should('be.true');\n  }",
      displayError: null,
      attempts: [
        {
          state: "passed",
          error: null,
          timings: {
            lifecycle: 35,
            "before each": [
              { hookId: "h1", fnDuration: 11, afterFnDuration: 0 },
              { hookId: "h2", fnDuration: 89, afterFnDuration: 0 },
            ],
            test: { fnDuration: 3, afterFnDuration: 0 },
            "after each": [
              { hookId: "h4", fnDuration: 12, afterFnDuration: 0 },
              { hookId: "h5", fnDuration: 9, afterFnDuration: 0 },
            ],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:08:58.160Z",
          wallClockDuration: 164,
          videoTimestamp: 14516,
          startedAt: "2023-09-14T03:08:58.160Z",
          duration: 164,
          screenshots: [],
        },
      ],
    },
    {
      testId: "r5",
      title: [
        "Failing test with 2 attempts, passed test and flaky test with 2 attempts",
        "should fail on the first attempt and pass on the second",
      ],
      state: "passed",
      body: "() => {\n    if (attempt === 0) {\n      attempt++;\n      cy.wrap(false).should('be.true'); // This will fail on the first attempt\n    } else {\n      cy.wrap(true).should('be.true'); // This will pass on the second attempt\n    }\n  }",
      displayError: null,
      attempts: [
        {
          state: "failed",
          error: {
            name: "AssertionError",
            message:
              "Timed out retrying after 4000ms: expected false to be true",
            stack:
              "    at Context.eval (webpack://cypress-13-demo/./cypress/e2e/b.spec.js:16:21)",
            codeFrame: {
              line: 16,
              column: 22,
              originalFile: "cypress/e2e/b.spec.js",
              relativeFile: "e2e/cypress-13-demo/cypress/e2e/b.spec.js",
              absoluteFile:
                "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/e2e/b.spec.js",
              frame:
                "  14 |     if (attempt === 0) {\n  15 |       attempt++;\n> 16 |       cy.wrap(false).should('be.true');  // This will fail on the first attempt\n     |                      ^\n  17 |     } else {\n  18 |       cy.wrap(true).should('be.true');   // This will pass on the second attempt\n  19 |     }",
              language: "js",
            },
          },
          timings: {
            lifecycle: 21,
            "before each": [
              { hookId: "h1", fnDuration: 8, afterFnDuration: 0 },
              { hookId: "h2", fnDuration: 54, afterFnDuration: 0 },
            ],
            test: { fnDuration: 3991, afterFnDuration: 234 },
            "after each": [
              { hookId: "h4", fnDuration: 14, afterFnDuration: 1 },
              { hookId: "h5", fnDuration: 44, afterFnDuration: 0 },
            ],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:08:58.325Z",
          wallClockDuration: 4371,
          videoTimestamp: 14681,
          startedAt: "2023-09-14T03:08:58.325Z",
          duration: 4371,
          screenshots: [
            {
              screenshotId: "xa6yo",
              name: "screenshot",
              testId: "r5",
              testAttemptIndex: 0,
              takenAt: "2023-09-14T03:09:02.403Z",
              path: "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/screenshots/b.spec.js/Failing test with 2 attempts, passed test and flaky test with 2 attempts -- should fail on the first attempt and pass on the second (failed).png",
              height: 1440,
              width: 2560,
            },
          ],
        },
        {
          state: "passed",
          error: null,
          timings: {
            lifecycle: 50,
            "before each": [
              { hookId: "h1", fnDuration: 8, afterFnDuration: 0 },
              { hookId: "h2", fnDuration: 103, afterFnDuration: 1 },
            ],
            test: { fnDuration: 3, afterFnDuration: 0 },
            "after each": [
              { hookId: "h4", fnDuration: 11, afterFnDuration: 0 },
              { hookId: "h5", fnDuration: 14, afterFnDuration: 0 },
            ],
            "after all": [{ hookId: "h3", fnDuration: 5, afterFnDuration: 0 }],
          },
          failedFromHookId: null,
          wallClockStartedAt: "2023-09-14T03:09:02.705Z",
          wallClockDuration: 202,
          videoTimestamp: 19061,
          startedAt: "2023-09-14T03:09:02.705Z",
          duration: 202,
          screenshots: [],
        },
      ],
    },
  ],
};
export const config = {
  additionalIgnorePattern: [],
  animationDistanceThreshold: 5,
  arch: "arm64",
  autoOpen: false,
  baseUrl: "https://todomvc.com/examples/vanillajs",
  blockHosts: null,
  browsers: [
    {
      name: "chrome",
      family: "chromium",
      channel: "stable",
      displayName: "Chrome",
      version: "116.0.5845.187",
      path: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
      minSupportedVersion: 64,
      majorVersion: "116",
    },
    {
      name: "edge",
      family: "chromium",
      channel: "stable",
      displayName: "Edge",
      version: "116.0.1938.81",
      path: "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
      minSupportedVersion: 79,
      majorVersion: "116",
    },
    {
      name: "electron",
      channel: "stable",
      family: "chromium",
      displayName: "Electron",
      version: "106.0.5249.51",
      path: "",
      majorVersion: 106,
    },
  ],
  chromeWebSecurity: true,
  clientCertificates: [],
  clientRoute: "/__/",
  configFile:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress.config.ts",
  cypressBinaryRoot:
    "/Users/miguelangarano/Library/Caches/Cypress/12.17.4/Cypress.app/Contents/Resources/app",
  cypressEnv: "production",
  defaultCommandTimeout: 4000,
  devServerPublicPathRoute: "/__cypress/src",
  downloadsFolder:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/downloads",
  env: {
    currents_temp_file:
      "/var/folders/1l/tzj2dqys6js7w35f8rx2jsq00000gn/T/tmp-45859-JGguqnT5L2dB",
    currents_debug_enabled: false,
  },
  excludeSpecPattern: "*.hot-update.js",
  execTimeout: 60000,
  experimentalCspAllowList: false,
  experimentalFetchPolyfill: false,
  experimentalInteractiveRunEvents: false,
  experimentalMemoryManagement: false,
  experimentalModifyObstructiveThirdPartyCode: false,
  experimentalOriginDependencies: false,
  experimentalRunAllSpecs: false,
  experimentalSingleTabRunMode: false,
  experimentalSkipDomainInjection: null,
  experimentalSourceRewriting: false,
  experimentalStudio: false,
  experimentalWebKitSupport: false,
  fileServerFolder:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo",
  fixturesFolder:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/fixtures",
  hosts: null,
  includeShadowDom: false,
  isInteractive: true,
  isTextTerminal: true,
  keystrokeDelay: 0,
  modifyObstructiveCode: true,
  morgan: false,
  namespace: "__cypress",
  numTestsKeptInMemory: 0,
  pageLoadTimeout: 60000,
  platform: "darwin",
  port: null,
  projectId: null,
  projectName: "cypress-13-demo",
  projectRoot:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo",
  rawJson: {
    video: true,
    e2e: {
      baseUrl: "https://todomvc.com/examples/vanillajs",
      supportFile: "cypress/support/e2e.ts",
      specPattern: "cypress/*/**/*.spec.js",
      setupNodeEvents: "[Function setupNodeEvents]",
    },
    component: {
      specPattern: ["pages/__tests__/*.spec.tsx"],
      setupNodeEvents: "[Function setupNodeEvents]",
      devServer: { framework: "next", bundler: "webpack" },
    },
    baseUrl: "https://todomvc.com/examples/vanillajs",
    supportFile: "cypress/support/e2e.ts",
    specPattern: "cypress/*/**/*.spec.js",
    setupNodeEvents: "[Function setupNodeEvents]",
    envFile: {},
    projectRoot:
      "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo",
    projectName: "cypress-13-demo",
    repoRoot:
      "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13",
  },
  redirectionLimit: 20,
  repoRoot:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13",
  report: true,
  reporter: "spec",
  reporterOptions: null,
  reporterRoute: "/__cypress/reporter",
  requestTimeout: 5000,
  resolved: {
    animationDistanceThreshold: { value: 5, from: "default" },
    arch: { value: "arm64", from: "default" },
    baseUrl: {
      value: "https://todomvc.com/examples/vanillajs",
      from: "config",
    },
    blockHosts: { value: null, from: "default" },
    chromeWebSecurity: { value: true, from: "default" },
    clientCertificates: { value: [], from: "default" },
    defaultCommandTimeout: { value: 4000, from: "default" },
    downloadsFolder: { value: "cypress/downloads", from: "default" },
    env: {
      currents_temp_file: {
        value:
          "/var/folders/1l/tzj2dqys6js7w35f8rx2jsq00000gn/T/tmp-45859-JGguqnT5L2dB",
        from: "cli",
      },
      currents_debug_enabled: { value: false, from: "cli" },
    },
    execTimeout: { value: 60000, from: "default" },
    experimentalCspAllowList: { value: false, from: "default" },
    experimentalFetchPolyfill: { value: false, from: "default" },
    experimentalInteractiveRunEvents: { value: false, from: "default" },
    experimentalRunAllSpecs: { value: false, from: "default" },
    experimentalMemoryManagement: { value: false, from: "default" },
    experimentalModifyObstructiveThirdPartyCode: {
      value: false,
      from: "default",
    },
    experimentalSkipDomainInjection: { value: null, from: "default" },
    experimentalOriginDependencies: { value: false, from: "default" },
    experimentalSourceRewriting: { value: false, from: "default" },
    experimentalSingleTabRunMode: { value: false, from: "default" },
    experimentalStudio: { value: false, from: "default" },
    experimentalWebKitSupport: { value: false, from: "default" },
    fileServerFolder: { value: "", from: "default" },
    fixturesFolder: { value: "cypress/fixtures", from: "default" },
    excludeSpecPattern: { value: "*.hot-update.js", from: "default" },
    includeShadowDom: { value: false, from: "default" },
    keystrokeDelay: { value: 0, from: "default" },
    modifyObstructiveCode: { value: true, from: "default" },
    nodeVersion: { from: "default" },
    numTestsKeptInMemory: { value: 0, from: "config" },
    platform: { value: "darwin", from: "default" },
    pageLoadTimeout: { value: 60000, from: "default" },
    port: { value: null, from: "default" },
    projectId: { value: null, from: "default" },
    redirectionLimit: { value: 20, from: "default" },
    reporter: { value: "spec", from: "default" },
    reporterOptions: { value: null, from: "default" },
    requestTimeout: { value: 5000, from: "default" },
    resolvedNodePath: { value: null, from: "default" },
    resolvedNodeVersion: { value: null, from: "default" },
    responseTimeout: { value: 30000, from: "default" },
    retries: {
      value: { runMode: 0, openMode: 0 },
      from: "default",
    },
    screenshotOnRunFailure: { value: true, from: "default" },
    screenshotsFolder: {
      value: "cypress/screenshots",
      from: "default",
    },
    slowTestThreshold: { value: 10000, from: "default" },
    scrollBehavior: { value: "top", from: "default" },
    supportFile: { value: "cypress/support/e2e.ts", from: "config" },
    supportFolder: { value: false, from: "default" },
    taskTimeout: { value: 60000, from: "default" },
    testIsolation: { value: true, from: "default" },
    trashAssetsBeforeRuns: { value: true, from: "default" },
    userAgent: { value: null, from: "default" },
    video: { value: true, from: "default" },
    videoCompression: { value: 32, from: "default" },
    videosFolder: { value: "cypress/videos", from: "default" },
    videoUploadOnPasses: { value: true, from: "default" },
    viewportHeight: { value: 660, from: "default" },
    viewportWidth: { value: 1000, from: "default" },
    waitForAnimations: { value: true, from: "default" },
    watchForFileChanges: { value: false, from: "config" },
    specPattern: { value: "cypress/*/**/*.spec.js", from: "config" },
    browsers: {
      value: [
        {
          name: "chrome",
          family: "chromium",
          channel: "stable",
          displayName: "Chrome",
          version: "116.0.5845.187",
          path: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
          minSupportedVersion: 64,
          majorVersion: "116",
        },
        {
          name: "edge",
          family: "chromium",
          channel: "stable",
          displayName: "Edge",
          version: "116.0.1938.81",
          path: "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
          minSupportedVersion: 79,
          majorVersion: "116",
        },
        {
          name: "electron",
          channel: "stable",
          family: "chromium",
          displayName: "Electron",
          version: "106.0.5249.51",
          path: "",
          majorVersion: 106,
        },
      ],
      from: "runtime",
    },
    hosts: { value: null, from: "default" },
    isInteractive: { value: true, from: "default" },
  },
  resolvedNodePath:
    "/Users/miguelangarano/.nvm/versions/node/v18.14.2/bin/node",
  resolvedNodeVersion: "18.14.2",
  responseTimeout: 30000,
  retries: { runMode: 0, openMode: 0 },
  screenshotOnRunFailure: true,
  screenshotsFolder:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/screenshots",
  scrollBehavior: "top",
  setupNodeEvents: "[Function setupNodeEvents]",
  slowTestThreshold: 10000,
  socketId: "ijm5bzfgh0",
  socketIoCookie: "__socket",
  socketIoRoute: "/__socket",
  specPattern: "cypress/*/**/*.spec.js",
  supportFile:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/support/e2e.ts",
  supportFolder:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/support",
  taskTimeout: 60000,
  testIsolation: true,
  trashAssetsBeforeRuns: true,
  userAgent: null,
  version: "12.17.4",
  video: true,
  videoCompression: 32,
  videoUploadOnPasses: true,
  videosFolder:
    "/Users/miguelangarano/Documents/GitHub/cypress-cloud-private-fix-cypress-13/e2e/cypress-13-demo/cypress/videos",
  viewportHeight: 660,
  viewportWidth: 1000,
  waitForAnimations: true,
  watchForFileChanges: false,
  testingType: "e2e",
};

export const all = {
  totalDuration: 33459,
  totalSuites: 5,
  totalPending: 1,
  totalFailed: 3,
  totalSkipped: 0,
  totalPassed: 4,
  totalTests: 8,
  runs: [specA, specE, specD, specC, specB],
  startedTestsAt: "2023-09-14T03:08:15.698Z",
  endedTestsAt: "2023-09-14T03:09:02.909Z",
  config,
  status: "finished",
  runUrl: "https://app.currents.dev/run/7dc0426fc25d30fe",
};
