import { expect } from "@jest/globals";

export const status = "OK";

export const data = {
  runId: expect.any(String),
  projectId: expect.any(String),
  createdAt: expect.any(String),
  tags: [],
  cypressVersion: expect.any(String),
  cancellation: null,
  timeout: { isTimeout: false },
  groups: [
    {
      groupId: expect.any(String),
      platform: {
        osName: expect.any(String),
        osVersion: expect.any(String),
        browserName: expect.any(String),
        browserVersion: expect.any(String),
      },
      createdAt: expect.any(String),
      instances: {
        overall: 5,
        claimed: 5,
        complete: 5,
        passes: 2,
        failures: 3,
      },
      tests: {
        overall: 8,
        passes: 4,
        failures: 3,
        pending: 1,
        skipped: 0,
        retries: 1,
        flaky: 1,
      },
    },
  ],
  meta: {
    ciBuildId: expect.any(String),
    commit: {
      branch: expect.any(String),
      remoteOrigin: expect.any(String),
      authorEmail: expect.any(String),
      authorName: expect.any(String),
      message: expect.any(String),
      sha: expect.any(String),
    },
    platform: {
      osName: expect.any(String),
      osVersion: expect.any(String),
      browserName: expect.any(String),
      browserVersion: expect.any(String),
    },
  },
  specs: [
    {
      groupId: expect.any(String),
      spec: "cypress/e2e/a.spec.js",
      instanceId: expect.any(String),
      claimedAt: expect.any(String),
      completedAt: expect.any(String),
      machineId: expect.any(String),
      worker: null,
      results: {
        videoUrl: expect.any(String),
        stats: {
          duration: expect.any(Number),
          endedAt: expect.any(String),
          startedAt: expect.any(String),
          failures: 1,
          passes: 0,
          pending: 0,
          skipped: 0,
          suites: 1,
          tests: 1,
          wallClockDuration: expect.any(Number),
          wallClockStartedAt: expect.any(String),
          wallClockEndedAt: expect.any(String),
        },
        screenshots: [
          {
            screenshotId: expect.any(String),
            name: null,
            testId: "r0",
            testAttemptIndex: 0,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
          {
            screenshotId: expect.any(String),
            name: null,
            testId: "r0",
            testAttemptIndex: 1,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
          {
            screenshotId: expect.any(String),
            name: null,
            testId: "r0",
            testAttemptIndex: 2,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
        ],
        exception: null,
        flaky: 0,
      },
    },
    {
      groupId: expect.any(String),
      spec: "cypress/e2e/b.spec.js",
      instanceId: expect.any(String),
      claimedAt: expect.any(String),
      completedAt: expect.any(String),
      machineId: expect.any(String),
      worker: null,
      results: {
        videoUrl: expect.any(String),
        stats: {
          duration: expect.any(Number),
          endedAt: expect.any(String),
          startedAt: expect.any(String),
          failures: 1,
          passes: 2,
          pending: 0,
          skipped: 0,
          suites: 1,
          tests: 3,
          wallClockDuration: expect.any(Number),
          wallClockStartedAt: expect.any(String),
          wallClockEndedAt: expect.any(String),
        },
        screenshots: [
          {
            screenshotId: expect.any(String),
            name: null,
            testId: "r0",
            testAttemptIndex: 0,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
          {
            screenshotId: expect.any(String),
            name: null,
            testId: "r0",
            testAttemptIndex: 1,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
          {
            screenshotId: expect.any(String),
            name: null,
            testId: "r0",
            testAttemptIndex: 2,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
          {
            screenshotId: expect.any(String),
            name: null,
            testId: "r2",
            testAttemptIndex: 0,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
        ],
        exception: null,
        flaky: 1,
      },
    },
    {
      groupId: expect.any(String),
      spec: "cypress/e2e/c.spec.js",
      instanceId: expect.any(String),
      claimedAt: expect.any(String),
      completedAt: expect.any(String),
      machineId: expect.any(String),
      worker: null,
      results: {
        videoUrl: null,
        stats: {
          duration: expect.any(Number),
          endedAt: expect.any(String),
          startedAt: expect.any(String),
          failures: 0,
          passes: 0,
          pending: 1,
          skipped: 0,
          suites: 1,
          tests: 1,
          wallClockDuration: expect.any(Number),
          wallClockStartedAt: expect.any(String),
          wallClockEndedAt: expect.any(String),
        },
        screenshots: [],
        exception: null,
        flaky: 0,
      },
    },
    {
      groupId: expect.any(String),
      spec: "cypress/e2e/d.spec.js",
      instanceId: expect.any(String),
      claimedAt: expect.any(String),
      completedAt: expect.any(String),
      machineId: expect.any(String),
      worker: null,
      results: {
        videoUrl: null,
        stats: {
          duration: expect.any(Number),
          endedAt: expect.any(String),
          startedAt: expect.any(String),
          failures: 0,
          passes: 2,
          pending: 0,
          skipped: 0,
          suites: 1,
          tests: 2,
          wallClockDuration: expect.any(Number),
          wallClockStartedAt: expect.any(String),
          wallClockEndedAt: expect.any(String),
        },
        screenshots: [
          {
            screenshotId: expect.any(String),
            name: "internal-assert-screenshot",
            testId: "r0",
            testAttemptIndex: 0,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
        ],
        exception: null,
        flaky: 0,
      },
    },
    {
      groupId: expect.any(String),
      spec: "cypress/e2e/e.spec.js",
      instanceId: expect.any(String),
      claimedAt: expect.any(String),
      completedAt: expect.any(String),
      machineId: expect.any(String),
      worker: null,
      results: {
        videoUrl: expect.any(String),
        stats: {
          duration: expect.any(Number),
          endedAt: expect.any(String),
          startedAt: expect.any(String),
          failures: 1,
          passes: 0,
          pending: 0,
          skipped: 0,
          suites: 1,
          tests: 1,
          wallClockDuration: expect.any(Number),
          wallClockStartedAt: expect.any(String),
          wallClockEndedAt: expect.any(String),
        },
        screenshots: [
          {
            screenshotId: expect.any(String),
            name: null,
            testId: "r0",
            testAttemptIndex: 0,
            takenAt: expect.any(String),
            screenshotURL: expect.any(String),
            height: 0,
            width: 0,
          },
        ],
        exception: null,
        flaky: 0,
      },
    },
  ],
  completionState: "COMPLETE",
  status: "FAILED",
};
