name: e2e-cypress-compatibility
on:
  push:

jobs:
  e2e-cypress-compatibility:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cypress-version: ["13", "12"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress ${{ matrix.cypress-version }}
        run: npm install cypress@${{ matrix.cypress-version }}

      - name: Build
        run: npm run build

      - name: Run compatibility tests
        working-directory: ./e2e/cypress-13-demo
        env:
          CURRENTS_API_KEY: ${{ secrets.CURRENTS_API_KEY }}
          CURRENTS_RUN_BASE_URL: ${{ secrets.CURRENTS_RUN_BASE_URL }}
          CURRENTS_PROJECT_ID: ${{ secrets.CURRENTS_PROJECT_ID }}
          CURRENTS_RECORD_KEY: ${{ secrets.CURRENTS_RECORD_KEY }}
          CURRENTS_USE_CYPRESS_VERSION: ${{ matrix.cypress-version }}

        run: >
          npx jest
